version: 0.2

phases:
  install:
    commands:
      - echo "🔍 Checking if 'SunBin' exists in index.html..."
  build:
    commands:
      - echo "Checking for 'SunBin' in index.html..."
      - |
        if grep -q "SunBin" index.html; then
          echo "✅ FOUND"
        else
          echo "❌ NOT FOUND"
          echo "===== FILE CONTENTS ====="
          cat index.html
          exit 1
        fi
